runtime: python312

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  FLASK_ENV: production
  SECRET_KEY: "dcc066b93de48b43fe46454cfbcd7b38d2f63beac9934f76f74582ae98b82140"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto